project:
  type: website
  output-dir: docs
  resources: 
    - "wavs/*.wav"
    - "samples*/*.wav"

website:
  title: "Indic-ParlerTTS Dataset"
  
  page-navigation: true
  sidebar:
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: pilotv1.qmd
        text: Pilot v1
      - section: "Pilot v2"
        contents:
        - href: pilotv2e2.qmd
          text: Epoch-2
        - href: pilotv2e5.qmd
          text: Epoch-5
        - section: Epoc-18
          contents:
          - href: pilotv2e18.qmd
            text: English-Hindi
          - href: pilotv2e18rasa.qmd
            text: Rasa Speakers
          - href: pilotv2e18lcsunita.qmd
            text: Sunita Long Context
          - href: pilotv2e18langs.qmd
            text: All Languages

css:
  - https://lalten.github.io/lmweb/style/latinmodern-sans.css
  - https://lalten.github.io/lmweb/style/latinmodern-roman.css
  - https://lalten.github.io/lmweb/style/latinmodern-mono.css
mainfont: "Latin Modern Sans"
fontsize: 14pt
fontfamilyoptions: "oblique"
monofont: "Latin Modern Mono"
highlight-style: "tango"


format:
  html:
    theme: 
      light: [zephyr, styles_light.scss]
      dark: [darkly, styles.scss]
    code-copy: true
    toc: true