project:
  type: website
  output-dir: docs
  resources: 
    - "wavs/*.wav"

css:
  - https://lalten.github.io/lmweb/style/latinmodern-sans.css
  - https://lalten.github.io/lmweb/style/latinmodern-roman.css
  - https://lalten.github.io/lmweb/style/latinmodern-mono.css
mainfont: "Latin Modern Sans"
fontsize: 14pt
fontfamilyoptions: "oblique"
monofont: "Latin Modern Mono"
highlight-style: "tango"


format:
  html:
    theme:
      light: [cosmo, styles_light.scss]
      dark: [cosmo, styles.scss]
    code-copy: true
    toc: true