# Pilot v2 Epoch-18

## English Samples

#### Sample 1

- **Language:** English
- **Text:** a trade was arranged with the richmond football club.
- **Transliteration:** Transliteration not available
- **Description:** A male speaker in his thirties speaking English with a United States accent delivers his speech in a close-sounding environment with great speech quality. His voice has a slightly high pitch and a slightly fast pace, while maintaining a slightly monotone tone. The overall effect is slightly clear, with minimal background noise.

{{< video samples5/sample_out_1.wav height="68" width="300" >}}


#### Sample 2

- **Language:** English
- **Text:** the image on the monument was promptly fixed.
- **Transliteration:** Transliteration not available
- **Description:** A female in her twenties speaks with a tense, rapid, United States accent, and slight background noise.

{{< video samples5/sample_out_2.wav height="68" width="300" >}}


#### Sample 3

- **Language:** English
- **Text:** WE OUGHT TO LOVE WELL , FOR THE LOVE IS SHORT .
- **Transliteration:** Transliteration not available
- **Description:** moderately deep voice, moderately slow, moderately unchanging

{{< video samples5/sample_out_3.wav height="68" width="300" >}}


#### Sample 4

- **Language:** English
- **Text:** in the meantime, i use a few different approaches.
- **Transliteration:** Transliteration not available
- **Description:** A young male speaker is speaking English with a United States accent. His voice sounds close-sounding with a slightly high pitch and good speech quality, reflecting a moderately dynamic tone. The pace of his delivery is slightly fast, making the overall audio sample slightly clear.

{{< video samples5/sample_out_4.wav height="68" width="300" >}}


#### Sample 5

- **Language:** English
- **Text:** 'Maybe, Rachel dear, you would like to drive a little?'
- **Transliteration:** Transliteration not available
- **Description:**  A female speaker with an American accent delivers an expressive and animated speech with a slightly high-pitch voice. She speaks slightly faster than normal and the recording is slightly noisy, but overall it's a clear andclose-sounding audio.

{{< video samples5/sample_out_5.wav height="68" width="300" >}}


#### Sample 6

- **Language:** English
- **Text:** everyone should have the right of education.
- **Transliteration:** Transliteration not available
- **Description:** male, fairly fast, adjacent, little background noise, constant tone, good speech quality, India accent

{{< video samples5/sample_out_6.wav height="68" width="300" >}}


#### Sample 7

- **Language:** English
- **Text:** EAT IT . YOU MUST KEEP UP YOUR STRENGTH .
- **Transliteration:** Transliteration not available
- **Description:** somewhat fast, adjacent, minimal noise distraction, vibrant tone, a bit unsatisfactory speech quality

{{< video samples5/sample_out_7.wav height="68" width="300" >}}


#### Sample 8

- **Language:** English
- **Text:** Such a dog the wise driver kills, or turns loose.
- **Transliteration:** Transliteration not available
- **Description:** The woman speaks English with a Gujarati accent, her voice slightly higher in pitch than average. She speaks with noticeable emotion, her delivery moderately dynamic and somewhat expressive, despite being delivered at a slow pace. The recording quality is excellent, capturing her voice with clarity in a room that sounds close and intimate. The combination of her unique accent and the high-quality audio results in a rich, engaging sound.

{{< video samples5/sample_out_8.wav height="68" width="300" >}}


#### Sample 9

- **Language:** English
- **Text:** The longer she thought, the more bewildered she grew.
- **Transliteration:** Transliteration not available
- **Description:** The audio sample features a very clear, flat tone with excellent American accent and outstanding speech quality.

{{< video samples5/sample_out_9.wav height="68" width="300" >}}


#### Sample 10

- **Language:** English
- **Text:** everything in the universe evolved, he said.
- **Transliteration:** Transliteration not available
- **Description:** The audio sample features a close, bass voice with a flat tone, Australian accent, and excellent speech quality.

{{< video samples5/sample_out_10.wav height="68" width="300" >}}


#### Sample 11

- **Language:** English
- **Text:** surveillance does not always bring security.
- **Transliteration:** Transliteration not available
- **Description:** male, a bit bass voice, fairly fast, nearby, unchanging tone, exceptional speech quality, United accent

{{< video samples5/sample_out_11.wav height="68" width="300" >}}


#### Sample 12

- **Language:** English
- **Text:** NOR TO OLYMPIA BRING MY VOTIVE OFFERING .
- **Transliteration:** Transliteration not available
- **Description:** distant, noise interference, unsatisfactory speech quality

{{< video samples5/sample_out_12.wav height="68" width="300" >}}


#### Sample 13

- **Language:** English
- **Text:** community role models are often overlooked and scarce.
- **Transliteration:** Transliteration not available
- **Description:** male, not very slow, proximate, fairly monotone, adequate speech quality, United accent

{{< video samples5/sample_out_13.wav height="68" width="300" >}}


#### Sample 14

- **Language:** English
- **Text:** "I am not going to confide in you; so don't think it.
- **Transliteration:** Transliteration not available
- **Description:** The audio sample features a male speaker with a high-pitched, close-sounding New Zealand accent and excellent speech quality.

{{< video samples5/sample_out_14.wav height="68" width="300" >}}


#### Sample 15

- **Language:** English
- **Text:** The scissors hung useless and rusting by his side.
- **Transliteration:** Transliteration not available
- **Description:**  A female speaker delivers her words with a monotone tone and at a moderate speed. The recording is of very good quality, with almost no background noise, and her voice comes across as clear and close-sounding.

{{< video samples5/sample_out_15.wav height="68" width="300" >}}


#### Sample 17

- **Language:** English
- **Text:** I HAVE AN IDEA ! BABYSITTER , DO TEN PUSH UPS !
- **Transliteration:** Transliteration not available
- **Description:** A speaker speaks in a highly expressive tone at a fast pace with a high pitch, delivering the speech with bad quality.

{{< video samples5/sample_out_17.wav height="68" width="300" >}}


#### Sample 18

- **Language:** English
- **Text:** she was assigned male at birth with the name "adam".
- **Transliteration:** Transliteration not available
- **Description:** The audio sample features a female speaker with a United States accent, pitchy voice, and acceptable speech quality.

{{< video samples5/sample_out_18.wav height="68" width="300" >}}


#### Sample 19

- **Language:** English
- **Text:** they were letters from the lodger's sweetheart, signed.
- **Transliteration:** Transliteration not available
- **Description:** A male teenager with a United States accent speaks quickly in a uniform, adjacent tone with acceptable speech quality.

{{< video samples5/sample_out_19.wav height="68" width="300" >}}


#### Sample 20

- **Language:** English
- **Text:** Let the Tiger eat the man, for men have no pity."
- **Transliteration:** Transliteration not available
- **Description:** The audio sample features a clear, monotone voice with a distinct Indian accent.

{{< video samples5/sample_out_20.wav height="68" width="300" >}}


#### Sample 21

- **Language:** English
- **Text:** That it was so much the worse for the government.
- **Transliteration:** Transliteration not available
- **Description:**  A female English speaker delivers her slightly expressive and animated speech very quickly at a slightly high-pitch, with a close-sounding and slightly noisy recording.

{{< video samples5/sample_out_21.wav height="68" width="300" >}}


#### Sample 23

- **Language:** English
- **Text:** she was assigned male at birth with the name "adam".
- **Transliteration:** Transliteration not available
- **Description:** A young woman speaks with an expressive tone and a high pitch, delivering her words at a moderate speed. Her voice is clear, with only a moderate background noise of ambient sound, and the sound of her words is close-sounding. She is speaking English with a United States accent and has good speech quality.

{{< video samples5/sample_out_23.wav height="68" width="300" >}}


#### Sample 24

- **Language:** English
- **Text:** IT'S DESCRIBED IN DETAIL ON PAGE THREE OF YOUR PROGRAM .
- **Transliteration:** Transliteration not available
- **Description:** A speaker in a slightly distant-sounding environment with moderate ambient sound background noise speaks in a slightly monotone tone at a slightly fast pace with a slightly low pitch, delivering with good speech quality.

{{< video samples5/sample_out_24.wav height="68" width="300" >}}


#### Sample 25

- **Language:** English
- **Text:** it was a great distance that he had to travel.
- **Transliteration:** Transliteration not available
- **Description:** The audio sample features a female speaker with an Assamese accent, speaking moderately slowly and clearly.

{{< video samples5/sample_out_25.wav height="68" width="300" >}}


#### Sample 26

- **Language:** English
- **Text:** "No; but he will, or I'll sue him and get judgment.
- **Transliteration:** Transliteration not available
- **Description:** Male, slightly low-pitch, very close-sounding, almost no noise, unvarying tone, wonderful speech quality, Unindentified accent

{{< video samples5/sample_out_26.wav height="68" width="300" >}}


#### Sample 27

- **Language:** English
- **Text:** i will expect a response before wednesday
- **Transliteration:** Transliteration not available
- **Description:** A young male speaker in his twenties, speaking English with a United States accent, delivers his speech in a close-sounding environment with slightly noisy background sound. His voice is characterized by a high pitch and a slightly fast pace, conveying a monotone tone that lacks dynamic expression, but overall maintains a good speech quality.

{{< video samples5/sample_out_27.wav height="68" width="300" >}}


#### Sample 28

- **Language:** English
- **Text:** She perceived this with annoyance and perplexity.
- **Transliteration:** Transliteration not available
- **Description:**  A female speaker with an American accent delivers a slightly expressive and animated speech with a slightly faster pace and a high-pitch voice. The recording is almost noiseless, with clear and close sounds.

{{< video samples5/sample_out_28.wav height="68" width="300" >}}


#### Sample 29

- **Language:** English
- **Text:** the sky that morning was clear and bright blue.
- **Transliteration:** Transliteration not available
- **Description:** The audio sample features a male voice with a deep, moderately fast, and clear England accent.

{{< video samples5/sample_out_29.wav height="68" width="300" >}}

## Hindi Samples

#### Sample 30

- **Language:** Hindi
- **Text:** अलग अलग जगह या कहे तो अलग अलग अलग अलग इस्थान जिसमें कुछ
- **Transliteration:** alaga alaga jagaha yā kahē tō alaga alaga alaga alaga isthāna jisamēṁ kucha
- **Description:** Female, easy-going, proximate, slight noise distraction, not very varied, somewhat poor speech quality

{{< video samples5/sample_out_30.wav height="68" width="300" >}}


#### Sample 31

- **Language:** Hindi
- **Text:** मध्य प्रदेश महाराष्ट उत्तर प्रदेश तमिलनाडु गुजरात
- **Transliteration:** madhya pradēśa mahārāṣṭa uttara pradēśa tamilanāḍu gujarāta
- **Description:** A man speaks in a deep voice at a normal pace with a somewhat flat tone. The recording quality is excellent, capturing his voice clearly as if he's speaking directly into the microphone in a room with a moderate amount of ambient noise. The combination of his low pitch and the high-quality audio results in a rich, resonant sound.

{{< video samples5/sample_out_31.wav height="68" width="300" >}}


#### Sample 33

- **Language:** Hindi
- **Text:** तो मेरे घर वालो ने उस कुत्ते को बच्चे को एक रात के लिए रखा
- **Transliteration:** tō mērē ghara vālō nē usa kuttē kō baccē kō ēka rāta kē liē rakhā
- **Description:** The audio sample is a recording of a male voice with a moderate noise level and slightly flat tone.

{{< video samples5/sample_out_33.wav height="68" width="300" >}}


#### Sample 34

- **Language:** Hindi
- **Text:** पाँच देशों के नाम अमेरिका अफ़्रीका जापान रशिया भारत
- **Transliteration:** pām̐ca dēśōṁ kē nāma amērikā afrīkā jāpāna raśiyā bhārata
- **Description:** The audio sample features a fairly monotone, adjacent tone with minimal noise distraction and adequate speech quality.

{{< video samples5/sample_out_34.wav height="68" width="300" >}}


#### Sample 35

- **Language:** Hindi
- **Text:** राजस्थान मध्य परदेश उत्तर परदेश जारखंड छत्तीसगढ़
- **Transliteration:** rājasthāna madhya paradēśa uttara paradēśa jārakhaṁḍa chattīsagaṛha
- **Description:** The audio sample is a recording of a female voice from a remote location with a moderately stable tone.

{{< video samples5/sample_out_35.wav height="68" width="300" >}}


#### Sample 38

- **Language:** Hindi
- **Text:** हमारी विविधता खतम हो जाती है क्योंकि हमारे पास एक हद तक
- **Transliteration:** hamārī vividhatā khatama hō jātī hai kyōṁki hamārē pāsa ēka hada taka
- **Description:** A man with a somewhat high-pitched voice speaks at a rapid pace in what seems to be a small, well-insulated room. His tone is somewhat flat and unemotional, and unfortunately, the good recording quality is offset by his poor diction, resulting in a bad speech quality.

{{< video samples5/sample_out_38.wav height="68" width="300" >}}


#### Sample 39

- **Language:** Hindi
- **Text:** मैंने स्कूल में डांस की व नृत्य की सभा में भाग लिया है
- **Transliteration:** maiṁnē skūla mēṁ ḍāṁsa kī va nr̥tya kī sabhā mēṁ bhāga liyā hai
- **Description:** Female, not very high voice, moderately slow, close

{{< video samples5/sample_out_39.wav height="68" width="300" >}}


#### Sample 40

- **Language:** Hindi
- **Text:** क्या मुझे तुरंत मैथ्यू टैकसिएर कोकोनट सिरप मिल सकता है
- **Transliteration:** kyā mujhē turaṁta maithyū ṭaikasiēra kōkōnaṭa sirapa mila sakatā hai
- **Description:** The audio sample is a fairly slow male voice with adjacent speech and minimal variation in tone.

{{< video samples5/sample_out_40.wav height="68" width="300" >}}